/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(preamble_prefixer.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(b7d461ddb358513bf8e8eb0d5e655ec6)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/bt4le/preamble_prefixer.h>
// pydoc.h is automatically generated in the build directory
#include <preamble_prefixer_pydoc.h>

void bind_preamble_prefixer(py::module& m)
{

    using preamble_prefixer    = ::gr::bt4le::preamble_prefixer;


    py::class_<preamble_prefixer, gr::block, gr::basic_block,
        std::shared_ptr<preamble_prefixer>>(m, "preamble_prefixer", D(preamble_prefixer))

        .def(py::init(&preamble_prefixer::make),
           D(preamble_prefixer,make)
        )
        



        ;




}








