/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-bt4le
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_BT4LE_API_H
#define INCLUDED_BT4LE_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_bt4le_EXPORTS
#define BT4LE_API __GR_ATTR_EXPORT
#else
#define BT4LE_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_BT4LE_API_H */
