/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(packet_sink_9_6.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(dba7504fd54ed9c278a2aa9dae9c0fa5)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/Zwave/packet_sink_9_6.h>
// pydoc.h is automatically generated in the build directory
#include <packet_sink_9_6_pydoc.h>

void bind_packet_sink_9_6(py::module& m)
{

    using packet_sink_9_6    = ::gr::Zwave::packet_sink_9_6;


    py::class_<packet_sink_9_6, gr::block, gr::basic_block,
        std::shared_ptr<packet_sink_9_6>>(m, "packet_sink_9_6", D(packet_sink_9_6))

        .def(py::init(&packet_sink_9_6::make),
           D(packet_sink_9_6,make)
        )
        



        ;




}








