/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(preamble.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(2275bea50c07b78502269d82c9829f4e)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/Zwave/preamble.h>
// pydoc.h is automatically generated in the build directory
#include <preamble_pydoc.h>

void bind_preamble(py::module& m)
{

    using preamble    = ::gr::Zwave::preamble;


    py::class_<preamble, gr::block, gr::basic_block,
        std::shared_ptr<preamble>>(m, "preamble", D(preamble))

        .def(py::init(&preamble::make),
           D(preamble,make)
        )
        



        ;




}








