/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(packet_sink_scapy.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(2a9dcc129a83b199e6abb818e67bfdb8)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/zigbee/packet_sink_scapy.h>
// pydoc.h is automatically generated in the build directory
#include <packet_sink_scapy_pydoc.h>

void bind_packet_sink_scapy(py::module& m)
{

    using packet_sink_scapy    = ::gr::zigbee::packet_sink_scapy;


    py::class_<packet_sink_scapy, gr::block, gr::basic_block,
        std::shared_ptr<packet_sink_scapy>>(m, "packet_sink_scapy", D(packet_sink_scapy))

        .def(py::init(&packet_sink_scapy::make),
           py::arg("threshold"),
           D(packet_sink_scapy,make)
        )
        



        ;




}








