/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(preamble_prefixer_scapy.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(1339eb43807e822014e35d032f096b6c)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/zigbee/preamble_prefixer_scapy.h>
// pydoc.h is automatically generated in the build directory
#include <preamble_prefixer_scapy_pydoc.h>

void bind_preamble_prefixer_scapy(py::module& m)
{

    using preamble_prefixer_scapy    = ::gr::zigbee::preamble_prefixer_scapy;


    py::class_<preamble_prefixer_scapy, gr::block, gr::basic_block,
        std::shared_ptr<preamble_prefixer_scapy>>(m, "preamble_prefixer_scapy", D(preamble_prefixer_scapy))

        .def(py::init(&preamble_prefixer_scapy::make),
           D(preamble_prefixer_scapy,make)
        )
        



        ;




}








