/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(strip_gr_header.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(f589fd0632972b64c14d29f630455ab6)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/scapy_radio/strip_gr_header.h>
// pydoc.h is automatically generated in the build directory
#include <strip_gr_header_pydoc.h>

void bind_strip_gr_header(py::module& m)
{

    using strip_gr_header    = ::gr::scapy_radio::strip_gr_header;


    py::class_<strip_gr_header, gr::block, gr::basic_block,
        std::shared_ptr<strip_gr_header>>(m, "strip_gr_header", D(strip_gr_header))

        .def(py::init(&strip_gr_header::make),
           py::arg("protocol_id"),
           D(strip_gr_header,make)
        )
        




        
        .def("protocol_id",&strip_gr_header::protocol_id,       
            D(strip_gr_header,protocol_id)
        )


        
        .def("set_protocol_id",&strip_gr_header::set_protocol_id,       
            py::arg("protocol_id"),
            D(strip_gr_header,set_protocol_id)
        )

        ;




}








