/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-scapy_radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_SCAPY_RADIO_API_H
#define INCLUDED_SCAPY_RADIO_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_scapy_radio_EXPORTS
#define SCAPY_RADIO_API __GR_ATTR_EXPORT
#else
#define SCAPY_RADIO_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_SCAPY_RADIO_API_H */
